### ISSUE TITLE
0 edges in network 'operon' error for Halobacterium test run

### ISSUE THREAD

**Issue by maxneal** [baliga-lab/cmonkey2#61]
I recently downloaded cmonkey2 and am getting an error when I try out the Halobacterium test run. This error appears on my Ubuntu virtual machine with MEME version 4.11.2 and on a Mac (El Capitan) with MEME version 4.10.1.

Input command:
bin/cmonkey2.sh --organism hal example_data/hal/halo_ratios5.tsv

Output:
Running cmonkey with 'python'
2016-10-26 17:04:43 INFO     checking MEME...
2016-10-26 17:04:43 INFO     Input matrix has # rows: 428, # columns: 5
2016-10-26 17:04:43 INFO     # clusters/row: 2
2016-10-26 17:04:43 INFO     # clusters/column: 29
2016-10-26 17:04:43 INFO     # CLUSTERS: 43
2016-10-26 17:04:43 INFO     use operons: 1
2016-10-26 17:04:43 INFO     using MEME version 4.11.2
2016-10-26 17:04:44 INFO     attempting automatic download of operons from Microbes Online
2016-10-26 17:04:44 INFO     NCBI CODE IS: 64091
2016-10-26 17:04:44 INFO     Automatically using STRING file in 'cache/64091.gz' (URL: http://networks.systemsbiology.net/string9/64091.gz)
2016-10-26 17:04:50 INFO     KEGG = 'Halobacterium NRC 1 uid57769' -> RSAT = 'Halobacterium_NRC_1_uid57769'
2016-10-26 17:04:50 INFO     Creating networks...
2016-10-26 17:04:50 INFO     stringdb.read_edges2()
2016-10-26 17:04:51 INFO     Finished loading cache/64091.gz
2016-10-26 17:04:51 INFO     Processing network 5%
2016-10-26 17:04:51 INFO     Processing network 10%
2016-10-26 17:04:51 INFO     Processing network 15%
2016-10-26 17:04:51 INFO     Processing network 20%
2016-10-26 17:04:51 INFO     Processing network 25%
2016-10-26 17:04:51 INFO     Processing network 30%
2016-10-26 17:04:51 INFO     Processing network 35%
2016-10-26 17:04:51 INFO     Processing network 40%
2016-10-26 17:04:51 INFO     Processing network 45%
2016-10-26 17:04:51 INFO     Processing network 50%
2016-10-26 17:04:52 INFO     Processing network 55%
2016-10-26 17:04:52 INFO     Processing network 60%
2016-10-26 17:04:52 INFO     Processing network 65%
2016-10-26 17:04:52 INFO     Processing network 70%
2016-10-26 17:04:52 INFO     Processing network 75%
2016-10-26 17:04:52 INFO     Processing network 80%
2016-10-26 17:04:52 INFO     Processing network 85%
2016-10-26 17:04:52 INFO     Processing network 90%
2016-10-26 17:04:52 INFO     Processing network 95%
2016-10-26 17:04:52 INFO     Processing network 100%
2016-10-26 17:04:52 WARNING  2191 (out of 471056) nodes not found in canonical gene names
2016-10-26 17:04:52 INFO     stringdb.read_edges2(), 8514 edges read, 227014 edges ignored
2016-10-26 17:04:52 INFO     MicrobesOnline - make_network()
2016-10-26 17:04:52 INFO     MicrobesOnline.get_operon_predictions_for(64091)
2016-10-26 17:04:52 INFO     0 prediction pairs read
2016-10-26 17:04:52 INFO     0 operons created
2016-10-26 17:04:52 INFO     0 edges computed
Traceback (most recent call last):
  File "/home/mneal/RNAseqTools/cmonkey2/bin/cmonkey2", line 36, in <module>
    cmonkey_run.run()
  File "/home/mneal/RNAseqTools/cmonkey2/cmonkey/cmonkey_run.py", line 512, in run
    self.prepare_run()
  File "/home/mneal/RNAseqTools/cmonkey2/cmonkey/cmonkey_run.py", line 474, in prepare_run
    thesaurus = self.organism().thesaurus()
  File "/home/mneal/RNAseqTools/cmonkey2/cmonkey/cmonkey_run.py", line 231, in organism
    self.**organism = self.make_organism()
  File "/home/mneal/RNAseqTools/cmonkey2/cmonkey/cmonkey_run.py", line 341, in make_organism
    self['fasta_file'])
  File "/home/mneal/RNAseqTools/cmonkey2/cmonkey/organism.py", line 244, in __init**
    fasta_file)
  File "/home/mneal/RNAseqTools/cmonkey2/cmonkey/organism.py", line 117, in **init**
    OrganismBase.**init**(self, code, network_factories, ratios=ratios)
  File "/home/mneal/RNAseqTools/cmonkey2/cmonkey/organism.py", line 72, in **init**
    self.__networks.append(make_network(self, ratios))
  File "/home/mneal/RNAseqTools/cmonkey2/cmonkey/microbes_online.py", line 234, in make_network
    ratios, check_size)
  File "/home/mneal/RNAseqTools/cmonkey2/cmonkey/network.py", line 150, in create
    raise Exception("Error: only %d edges in network '%s'" % (len(network_edges), name))
Exception: Error: only 0 edges in network 'operons'

**Comment by weiju** [comment]
Thank you for reporting this,

it seems there has been a temporary issue with MicrobesOnline, which was fixed.
Does this work for you now ?

**Comment by maxneal** [comment]
I tried the test run again just now. I still get the same error.

**Comment by weiju** [comment]
Thanks, could you please make sure that your cache directory is completely empty and retry ? Just to make sure the RSAT information got correctly read, because usually this type of error is caused by a mismatch of gene names.

BTW, MEME 4.11.x versions currently do not work with cmonkey2.

**Comment by maxneal** [comment]
After I cleared the cache it ran and completed successfully. (And FYI I had switched to meme 4.9.1 a couple weeks ago.) Thanks!

**Comment by weiju** [comment]
great to hear it works for you now, thanks !
